### ISSUE TITLE
keyboard input broken with SDL2

### ISSUE THREAD

**Issue by phaethonfire** [podiki/libtcod-mac#1] opened 2014-10-16 14:01 UTC
This repo is behind the original trunk.  There is a bug with SDL2 described here:
https://bitbucket.org/jice/libtcod/issue/39/proposed-sdl2-unknown-pressed-character

If you can merge in the changed from jice's repo, it will fix them.  With this repo, the TCOD_key_t foo.shift boolean wasn't working and I couldn't get capital letters.  The newest libtcod adds a "text" element to get the right input from SDL2.

All that said, thanks for posting this fork.  The makefile worked great and saved me a headache.

**Comment by podiki** [comment] 2014-10-17 06:30
Hello! Thanks for taking a look at my fork. Can you give me a test case? The only changes upstream since I created this fork have been some minor things related to Windows support. I just checked the issue you mentioned and the source here is up to date with those changes. Can you please double check or let me know what to reproduce?

Thanks!

**Comment by podiki** [comment] 2015-06-17 21:54
Closing this since as far as I can tell these changes were already in.

**Closed as completed by podiki** 2015-06-17 21:54 UTC
