### ISSUE TITLE
path_compute causes Segmentation Fault 11

### ISSUE THREAD

**Issue by atomdmac** [podiki/libtcod-mac#7] opened 2016-05-10 12:13 UTC
Hi there!

Thank you very much for your work on making this port available!  I've run into very few issues with it save for this one :P  However, there is certainly a chance that I simply compiled the source wrong or something...

It seems that whenever I try to use the libtcod.path_compute() method from Python 2.7.10 on OS X (El Capitan) Python crashes with "Segmentation fault: 11".  There is no other output.

Has anyone else experienced this issue?  I've spent a little time searching the net but haven't found anyone else discussing this precise issue...

Please let me know if I can provide any additional information.  I'm a C newbie so I'm still not sure what kinds of debug information is available/useful.

Thanks!

**Comment by podiki** [comment] 2016-05-10 18:07
Hello,

I'm happy to help if I can, but I have not looked at this code in some time. Additionally, libtcod development has been picked up again and can be found on [bitbucket](https://bitbucket.org/libtcod/libtcod). There is no Mac support there, and this one is not up to date with current development. It would be good to fold in Mac support upstream, but I have not had a chance yet (you are welcome to help!).

Anyway, on to your issue. Do you have a minimal example that produces this error? That would be easiest for me to look into. We can also try on another (non-Mac) system to see if the error is still in upstream.

**Comment by atomdmac** [comment] 2016-05-11 00:21
I'm actually in the process of learning C right now.  Hopefully I can contribute to the OSX support migration as part of that effort.

At any rate, here is the least amount of code necessary to reproduce the issue that I'm seeing:
http://pastebin.com/85c2ub0S

**Comment by podiki** [comment] 2016-05-11 18:34
Hopefully the Mac port related stuff is still just some lightly modified makefiles and such. I haven't tried it with the current development code of libtcod though.

Ok, I can verify that the python code you posted does lead to a crash on Mac. Have you tried on another OS? I can give it a shot later. Also, could try seeing if people using the current version of libtcod have the same error.

**Comment by podiki** [comment] 2016-05-11 18:49
Hmm, perhaps the problem is that your example does not have everything it needs to work correctly? The pathfinding example in samples.py works. (Note that the "custom listener" portion of the sample tests does not seem to work as is, but you can just comment it out.)

Edit: That does not use `path_new_using_function` though, maybe that is where we need to investigate.

**Comment by jdob** [comment] 2016-05-11 18:54
Dumb question, but did you copy both libtcod.py and cprotos.py to your codebase? I ran into a segfault with console_blit when I fist started my project because I didn't include them both. It threw me off because most of the functionality besides the blit worked (i wasn't trying paths at the time)

**Comment by podiki** [comment] 2016-05-11 19:14
Python should throw an error if you do not have cprotos.py available as well, as libtcodpy.py imports it if on Mac.

**Comment by atomdmac** [comment] 2016-05-12 01:32
Thanks for taking a look at this!  I've double-checked and can confirm that
I did copy both libtcod.py and cprotos.py to my codebase.  I haven't had
any issues with console_blit either so I'm fairly certain I have all of the
necessary library files...

I can also confirm that the path finding samples that come with libtcod
appear to be working as designed.  I did notice that they use
path_new_using_map rather than path_new_using_function (which is what my
code uses).  I'm not in a position to test just at the moment but I'll
re-run my sample code soon using path_new_using_map instead and see if that
works.  Will report back soon.

Thanks again for your help!

**Comment by atomdmac** [comment] 2016-05-12 01:46
Update!  I was able to modify my sample code to show that the issue does _not_ occur when calculating a path from a map (i.e. path_new_using_map).  The issue only occurs when using a callback to calculate the path (i.e. path_new_using_function and dijkstra_new_using_function).

Here's a pastebin for your edification:
http://pastebin.com/PWBHXgLA

**Comment by podiki** [comment] 2016-05-12 02:31
I can confirm with libtcod-1.5.1 on linux that there is a seg fault in the first example (using a function) but not the second (using a map). So either the problem is upstream (how python interfaces with passing a function to libtcod) or in the python code you are trying to use. I have not tried to use that function before, `path_new_using_function`, but we should look into that.

**Comment by atomdmac** [comment] 2016-05-15 21:06
One issue might be that in cprotos.py:854-855 are commented out.  Un-commenting yields an error, however:

```
Traceback (most recent call last):
  File "osx_bug.py", line 1, in <module>
    import libtcodpy as libtcod
  File "/Users/atommac/Code/roguelike-python-tutorial/libtcodpy.py", line 129, in <module>
    setup_protos(_lib)
  File "/Users/atommac/Code/roguelike-python-tutorial/cprotos.py", line 855, in setup_protos
    lib.TCOD_path_new_using_function.argtypes=[c_int, c_int, TCOD_path_func_t ,c_void_p, c_float ]
NameError: global name 'TCOD_path_func_t' is not defined
```

Do you happen to have any idea where TCOD_path_func_t is supposed to be defined?  I'm not even totally sure why it's a custom type (since my knowledge of C and how it interacts with python is quite limited).

On a related note: from looking at the function definition for path_new_using_function in libtcodpy.py:1558, it looks like it returns a tuple rather than just a path.  I'm not sure if that has anything to do with the problem but I thought that was interesting since the example [here](http://roguecentral.org/doryen/data/libtcod/doc/1.5.1/html2/path_init.html?c=false&cpp=false&cs=false&py=true&lua=false) doesn't seem to show that as the expected behavior.

**Comment by podiki** [comment] 2016-05-21 06:15
Interesting. Another function callback method is commented out in cprotos.py, `TCOD_dijkstra_new_using_function`. Maybe this is an upstream issue, but to be sure we should be certain the code you are using that crashes is supposed to work correctly in the first place...

**Comment by podiki** [comment] 2017-02-22 02:25
As this repository is woefully out of date and mac builds with the recent versions of libtcod, I will close this and refer you to [upstream](https://bitbucket.org/libtcod/libtcod/issues?status=new&status=open).

**Closed as completed by podiki** 2017-02-22 02:25 UTC
